version: 2
python:
  install:
  - path: .
    extra_requirements:
      - doc

# https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py

# required boilerplate readthedocs/readthedocs.org#10401
build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  # post-checkout job to ensure the clone isn't shallow jaraco/skeleton#114
  jobs:
    post_checkout:
    - git fetch --unshallow || true
